      character*3 titles(26)
      titles(1)='RHO'
      titles(2)='NL1'
      titles(3)='NL2'
      titles(4)='NL3'
      titles(5)='NL4'
      titles(6)='DIL'
      titles(7)='VOF'
      titles(8)='ZPT'
      titles(9)='TFF'
      titles(10)='LGG'
      titles(11)='FEH'
      titles(12)='FFF'
      titles(13)='OBL'
      titles(14)='OMG'
      titles(15)='BET'
      titles(16)='EP1'
      titles(17)='PE1'
      titles(18)='BB1'
      titles(19)='RD1'
      titles(20)='EC1'
      titles(21)='ES1'
      titles(22)='KR1'
      titles(23)='TE1'
      titles(24)='EL1'
      titles(25)='AL1'
      titles(26)='RT1'
      